n#include<iostream.h>
#include<conio.h>

void main() { clrscr();
	int b=21,a=61;

	clrscr();
	cout<<"Addition of "<<a<<" and "<<b<<" is : "<<a+b<<endl;
	cout<<"Substraction of "<<a<<" and "<<b<<" is "<<a-b<<endl;
	cout<<"Multiplication of " <<a<<" and "<<b<<" is "<<a*b<<endl;
	cout<<"Quotient of "<<a<<" and "<<b<<" is "<<a/b<<endl;
	cout<<"Remainder of "<<a<<" and "<<b<<" is "<<a%b<<endl;
	getch();
	}
